type User @table(key: ["id"]) @auth(
  level: USER,
  read: { expr: "auth.uid == id" },
  write: { expr: "auth.uid == id" }
) {
  id: String! @default(expr: "auth.uid")
  username: String!
  email: String!
  createdAt: Timestamp! @default(expr: "request.time")
  displayName: String
  profilePictureUrl: String
}

type Movie @table {
  tmdbId: String!
  title: String!
  releaseYear: Int!
  createdAt: Timestamp! @default(expr: "request.time")
  description: String
  posterUrl: String
  backdropUrl: String
  genres: [String]
  runtimeMinutes: Int
  tmdbRating: Float
}

type Anime @table {
  malId: String!
  title: String!
  releaseYear: Int!
  createdAt: Timestamp! @default(expr: "request.time")
  description: String
  posterUrl: String
  backdropUrl: String
  genres: [String]
  episodesCount: Int
  malRating: Float
}

type WatchHistory @table @auth(
  level: USER,
  read: { expr: "auth.uid == user.id" },
  write: { expr: "auth.uid == user.id" }
) {
  user: User!
  mediaType: String!
  movieId: Movie
  animeId: Anime
  watchedAt: Timestamp! @default(expr: "request.time")
}

type WatchlistItem @table @auth(
  level: USER,
  read: { expr: "auth.uid == user.id" },
  write: { expr: "auth.uid == user.id" }
) {
  user: User!
  mediaType: String!
  movieId: Movie
  animeId: Anime
  addedAt: Timestamp! @default(expr: "request.time")
}